name: "Test Framework Compose Filename - Shared"

on:
  workflow_call:

jobs:
  test-action:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            expected-platform-alias: "ubuntu22.04-x86_64"
            expected-packaging: "DEB"
            expected-extension: "deb"
          # - os: windows-latest
          #   expected-platform-alias: "win64"
          #   expected-packaging: "NSIS"
          #   expected-extension: "exe"
          # - os: macos-latest
          #   expected-platform-alias: "macos13-x86_64"
          #   expected-packaging: "PKG"
          #   expected-extension: "pkg"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test framework compose filename with default arguments
        id: framework-compose-filename-default-args
        uses: ./framework-compose-filename
      
      - name: Verify framework compose filename with default arguments
        shell: bash
        run: |
          filename="${{ steps.framework-compose-filename-default-args.outputs.filename }}"

          expected_tag=$(gh release list --repo openDAQ/openDAQ --json tagName,isLatest -q '.[] | select(.isLatest == true) | .tagName')
          IFS='.' read -r major minor patch <<< "${expected_tag#v}"

          expected_filename="opendaq-${major}.${minor}.${patch}-${{ matrix.expected-platform-alias }}.${{ matrix.expected-extension }}"

          if [[ "${expected_filename}" != "${filename}" ]]; then
            echo "::error ::❌ openDAQ framework package filename mismatches"
            echo "::error ::  - expected...: ${expected_filename}"
            echo "::error ::  - actual.....: ${filename}"
            exit 1
          fi

          echo "✅ openDAQ framework package filename matches expectations"
          echo "   - filename: ${filename}"
