name: Test All Actions

on:
  push:
    branches:
      - main

jobs:
  test-actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        action: [
            framework-download-artifact, 
            framework-download-release, 
            framework-install
            ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
