name: "Test Framework Compose Filename Action"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/test-framework-compose-filename.yml'
      - '.github/actions/framework-compose-filename/action.yml'
      - '.github/scripts/**'
  pull_request:
    paths:
      - '.github/workflows/test-framework-compose-filename.yml'
      - '.github/actions/framework-compose-filename/action.yml'
      - '.github/scripts/**'

jobs:
  # ============================================================================
  # Job 1: Platform detection test
  # Test auto-detection of platform + packaging on different OS/arch
  # Version is fixed: v1.40.9
  # ============================================================================
  test-platform-detection:
    name: Detect ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu x86_64
          - os: ubuntu-22.04
            expected-platform: ubuntu22.04-x86_64
            expected-extension: deb
          - os: ubuntu-24.04
            expected-platform: ubuntu24.04-x86_64
            expected-extension: deb
          
          # Ubuntu arm64
          - os: ubuntu-22.04-arm
            expected-platform: ubuntu22.04-arm64
            expected-extension: deb
          - os: ubuntu-24.04-arm
            expected-platform: ubuntu24.04-arm64
            expected-extension: deb
          
          # macOS Intel (x86_64)
          - os: macos-13
            expected-platform: macos13-x86_64
            expected-extension: tar.gz
          
          # macOS Apple Silicon (arm64)
          - os: macos-14
            expected-platform: macos14-arm64
            expected-extension: tar.gz
          - os: macos-15
            expected-platform: macos15-arm64
            expected-extension: tar.gz
          
          # Windows (only latest, always x64)
          - os: windows-latest
            expected-platform: win64
            expected-extension: exe
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Run action with fixed version
        id: action
        uses: ./framework-compose-filename
        with:
          version: v1.40.9
      
      - name: Validate filename
        shell: bash
        env:
          EXPECTED_PLATFORM: ${{ matrix.expected-platform }}
          EXPECTED_EXTENSION: ${{ matrix.expected-extension }}
          ACTUAL_FILENAME: ${{ steps.action.outputs.filename }}
        run: |
          expected_pattern="opendaq-v1.40.9-${EXPECTED_PLATFORM}.${EXPECTED_EXTENSION}"
          
          if [ "$ACTUAL_FILENAME" = "$expected_pattern" ]; then
            echo "PASS: $ACTUAL_FILENAME"
            exit 0
          else
            echo "FAIL: Filename mismatch"
            echo "  Expected: $expected_pattern"
            echo "  Got:      $ACTUAL_FILENAME"
            exit 1
          fi

  # ============================================================================
  # Job 2: Explicit parameters test
  # Test 1: Fixed version v1.40.9 + explicit platforms
  # Test 2: Fixed platform ubuntu22.04-x86_64 + latest version
  # ============================================================================
  test-explicit-parameters:
    name: ${{ matrix.test-name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Test explicit platforms with fixed version
          - test-name: "Platform ubuntu20.04-x86_64"
            test-type: explicit-platform
            version: v1.40.9
            platform: ubuntu20.04-x86_64
            expected-filename: opendaq-v1.40.9-ubuntu20.04-x86_64.deb
          
          - test-name: "Platform ubuntu22.04-arm64"
            test-type: explicit-platform
            version: v1.40.9
            platform: ubuntu22.04-arm64
            expected-filename: opendaq-v1.40.9-ubuntu22.04-arm64.deb
          
          - test-name: "Platform debian11-x86_64"
            test-type: explicit-platform
            version: v1.40.9
            platform: debian11-x86_64
            expected-filename: opendaq-v1.40.9-debian11-x86_64.deb
          
          - test-name: "Platform macos14-arm64"
            test-type: explicit-platform
            version: v1.40.9
            platform: macos14-arm64
            expected-filename: opendaq-v1.40.9-macos14-arm64.tar.gz
          
          - test-name: "Platform win64"
            test-type: explicit-platform
            version: v1.40.9
            platform: win64
            expected-filename: opendaq-v1.40.9-win64.exe
          
          # Test latest version with fixed platform
          - test-name: "Latest version"
            test-type: latest-version
            platform: ubuntu22.04-x86_64
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      # Get latest version for latest-version test
      - name: Get latest version
        if: matrix.test-type == 'latest-version'
        id: latest-version
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version=$(gh release list --repo openDAQ/openDAQ --json tagName,isLatest -q '.[] | select(.isLatest == true) | .tagName')
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Latest version: $version"
      
      - name: Run action
        id: action
        uses: ./framework-compose-filename
        with:
          version: ${{ matrix.version }}
          platform: ${{ matrix.platform }}
      
      # Validate explicit platform test
      - name: Validate explicit platform
        if: matrix.test-type == 'explicit-platform'
        shell: bash
        env:
          EXPECTED_FILENAME: ${{ matrix.expected-filename }}
          ACTUAL_FILENAME: ${{ steps.action.outputs.filename }}
        run: |
          if [ "$ACTUAL_FILENAME" = "$EXPECTED_FILENAME" ]; then
            echo "PASS: $ACTUAL_FILENAME"
            exit 0
          else
            echo "FAIL: Filename mismatch"
            echo "  Expected: $EXPECTED_FILENAME"
            echo "  Got:      $ACTUAL_FILENAME"
            exit 1
          fi
      
      # Validate latest version test
      - name: Validate latest version
        if: matrix.test-type == 'latest-version'
        shell: bash
        env:
          EXPECTED_VERSION: ${{ steps.latest-version.outputs.version }}
          EXPECTED_PLATFORM: ${{ matrix.platform }}
          ACTUAL_FILENAME: ${{ steps.action.outputs.filename }}
        run: |
          expected_filename="opendaq-${EXPECTED_VERSION}-${EXPECTED_PLATFORM}.deb"
          
          if [ "$ACTUAL_FILENAME" = "$expected_filename" ]; then
            echo "PASS: $ACTUAL_FILENAME"
            exit 0
          else
            echo "FAIL: Filename mismatch"
            echo "  Expected: $expected_filename"
            echo "  Got:      $ACTUAL_FILENAME"
            exit 1
          fi

  # ============================================================================
  # Job 3: Test summary
  # ============================================================================
  test-summary:
    name: Test Summary
    runs-on: ubuntu-latest
    needs: [test-platform-detection, test-explicit-parameters]
    if: always()
    
    steps:
      - name: Generate summary
        shell: bash
        run: |
          echo "# Test Results Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          # Determine overall status
          overall_status="PASS"
          if [ "${{ needs.test-platform-detection.result }}" != "success" ] || \
             [ "${{ needs.test-explicit-parameters.result }}" != "success" ]; then
            overall_status="FAIL"
          fi
          
          # Overall status with icon
          if [ "$overall_status" = "PASS" ]; then
            echo "## Overall Status: ✅ PASS" >> $GITHUB_STEP_SUMMARY
          else
            echo "## Overall Status: ❌ FAIL" >> $GITHUB_STEP_SUMMARY
          fi
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Test Suites" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Test Suite | Result | Test Cases |" >> $GITHUB_STEP_SUMMARY
          echo "|------------|--------|------------|" >> $GITHUB_STEP_SUMMARY
          
          # Platform detection
          status="${{ needs.test-platform-detection.result }}"
          icon="❓"
          case "$status" in
            success) icon="✅" ;;
            failure) icon="❌" ;;
            cancelled) icon="⏭️" ;;
            skipped) icon="⏭️" ;;
          esac
          echo "| Platform Detection | $icon $status | 8 OS/arch combinations |" >> $GITHUB_STEP_SUMMARY
          
          # Explicit parameters
          status="${{ needs.test-explicit-parameters.result }}"
          icon="❓"
          case "$status" in
            success) icon="✅" ;;
            failure) icon="❌" ;;
            cancelled) icon="⏭️" ;;
            skipped) icon="⏭️" ;;
          esac
          echo "| Explicit Parameters | $icon $status | 5 platforms + latest version |" >> $GITHUB_STEP_SUMMARY
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Test Coverage" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Platform Detection (version=v1.40.9)" >> $GITHUB_STEP_SUMMARY
          echo "- Ubuntu 22.04 x86_64" >> $GITHUB_STEP_SUMMARY
          echo "- Ubuntu 24.04 x86_64" >> $GITHUB_STEP_SUMMARY
          echo "- Ubuntu 22.04 arm64" >> $GITHUB_STEP_SUMMARY
          echo "- Ubuntu 24.04 arm64" >> $GITHUB_STEP_SUMMARY
          echo "- macOS 13 Intel (x86_64)" >> $GITHUB_STEP_SUMMARY
          echo "- macOS 14 Apple Silicon (arm64)" >> $GITHUB_STEP_SUMMARY
          echo "- macOS 15 Apple Silicon (arm64)" >> $GITHUB_STEP_SUMMARY
          echo "- Windows latest (x64)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Explicit Parameters" >> $GITHUB_STEP_SUMMARY
          echo "- **Fixed version (v1.40.9)** + 5 explicit platforms" >> $GITHUB_STEP_SUMMARY
          echo "- **Latest version** + fixed platform (ubuntu22.04-x86_64)" >> $GITHUB_STEP_SUMMARY
          
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ "$overall_status" = "PASS" ]; then
            echo "All tests passed successfully! 🎉" >> $GITHUB_STEP_SUMMARY
          else
            echo "⚠️ Some tests failed. Check individual job logs for details." >> $GITHUB_STEP_SUMMARY
          fi
          
          # Always exit 0 so summary is displayed
          # Workflow status is determined by needs.*.result
          exit 0
